version: '3.4'

services:
  hrm.interview.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  hrm.recruitment.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  hrm.onboard.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  hrm.authen.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

